### ISSUE TITLE
README, the Root Doc -- Screenies?

### ISSUE THREAD

**Issue by lief-erickson** [briandominick/codewriting#28]
> If all you showed me in the last section was screenies or a demo, it's time to get me up and running.

Screenies? I've been in the tech comm field for 20 years and never seen this word. But [Urban Dictionary](https://www.urbandictionary.com/define.php?term=screenies) does define the word to mean _screen shot_. I'm not sure that I would want Urban Dictionary to be my primary source for definitions though. But it's not my book. I'll merely politely suggest that it be changed in favor of a more neutral and understood term (especially by English as second language readers).

**Comment by briandominick** [comment]
I am a weird dude. It's a free book. Readers are going to have to suffer through some of my quirks. I use "screenies" at work, and I've made directories called `images/screenies/`. I'm more fun than frustrating, I promise. ;-)

**Comment by lief-erickson** [comment]
Nothing to see here. Move along.
