### ISSUE TITLE
The link to Codewriting site in Readme is incorrect

### ISSUE THREAD

**Issue by 8thHalfHour** [briandominick/codewriting#52]
The link at the end of the Readme that refers to codewriting.org is misspelled.

Current link -> https://codewriing.org

Like should be -> https://codewriting.org

It's just a typo, but I thought it might matter to anyone else who is as Type-A about docs as I am! :D

**Comment by briandominick** [comment]
Gah, thanks Charisma. Embarrassed but grateful. #53
